"""Initial migration for Supabase PostgreSQL

Revision ID: 4d117b316d9d
Revises: 
Create Date: 2025-12-18 14:34:36.264522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4d117b316d9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('parent_guid', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('placeholder', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_guid'], ['accounts.guid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_accounts_guid'), 'accounts', ['guid'], unique=False)
    op.create_table('customers',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_customers_guid'), 'customers', ['guid'], unique=False)
    op.create_table('employees',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('acl', sa.TEXT(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_employees_guid'), 'employees', ['guid'], unique=False)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    op.create_table('slots',
    sa.Column('obj_guid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slot_type', sa.String(length=50), nullable=False),
    sa.Column('string_val', sa.TEXT(), nullable=True),
    sa.Column('numeric_val', sa.NUMERIC(precision=18, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('obj_guid', 'name')
    )
    op.create_table('transactions',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('post_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enter_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_transactions_guid'), 'transactions', ['guid'], unique=False)
    op.create_table('vendors',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_vendors_guid'), 'vendors', ['guid'], unique=False)
    op.create_table('invoices',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('owner_guid', sa.String(length=36), nullable=False),
    sa.Column('customer_guid', sa.String(length=36), nullable=True),
    sa.Column('post_txn', sa.String(length=36), nullable=True),
    sa.Column('date_posted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_guid'], ['customers.guid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['post_txn'], ['transactions.guid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_invoices_guid'), 'invoices', ['guid'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=True)
    op.create_table('purchase_bills',
    sa.Column('guid', mysql.CHAR(length=36), nullable=False),
    sa.Column('vendor_guid', sa.String(length=36), nullable=False),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('post_txn_guid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_txn_guid'], ['transactions.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_guid'], ['vendors.guid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_purchase_bills_bill_number'), 'purchase_bills', ['bill_number'], unique=True)
    op.create_index(op.f('ix_purchase_bills_guid'), 'purchase_bills', ['guid'], unique=True)
    op.create_index(op.f('ix_purchase_bills_status'), 'purchase_bills', ['status'], unique=False)
    op.create_table('splits',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('txn_guid', sa.String(length=36), nullable=False),
    sa.Column('account_guid', sa.String(length=36), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('reconcile_state', sa.String(length=1), server_default='n', nullable=False),
    sa.Column('reconcile_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('quantity_num', sa.Integer(), nullable=False),
    sa.Column('quantity_denom', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_guid'], ['accounts.guid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['txn_guid'], ['transactions.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_splits_account_guid'), 'splits', ['account_guid'], unique=False)
    op.create_index(op.f('ix_splits_guid'), 'splits', ['guid'], unique=False)
    op.create_index(op.f('ix_splits_txn_guid'), 'splits', ['txn_guid'], unique=False)
    op.create_table('entries',
    sa.Column('guid', sa.String(length=36), nullable=False),
    sa.Column('invoice_guid', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('account_guid', sa.String(length=36), nullable=False),
    sa.Column('quantity_num', sa.Integer(), nullable=False),
    sa.Column('quantity_denom', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discounted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_guid'], ['accounts.guid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_guid'], ['invoices.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_entries_guid'), 'entries', ['guid'], unique=False)
    op.create_index(op.f('ix_entries_invoice_guid'), 'entries', ['invoice_guid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entries_invoice_guid'), table_name='entries')
    op.drop_index(op.f('ix_entries_guid'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_splits_txn_guid'), table_name='splits')
    op.drop_index(op.f('ix_splits_guid'), table_name='splits')
    op.drop_index(op.f('ix_splits_account_guid'), table_name='splits')
    op.drop_table('splits')
    op.drop_index(op.f('ix_purchase_bills_status'), table_name='purchase_bills')
    op.drop_index(op.f('ix_purchase_bills_guid'), table_name='purchase_bills')
    op.drop_index(op.f('ix_purchase_bills_bill_number'), table_name='purchase_bills')
    op.drop_table('purchase_bills')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_guid'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_vendors_guid'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_transactions_guid'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('slots')
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_guid'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_customers_guid'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_accounts_guid'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
